var outbrain_dual_version="6.5.1.1",outbrain_dual_template_object=typeof outbrain_dual_template_object=="function"?outbrain_dual_template_object:function(o){var k=this;outbrain_dual_template_object.baseConstructor.call(this,o);this.imagesPreload=function(){};this.positionFirstLine=this.positionSecondLine=false;this.positionRec=this.positionDynSecondLine=true;this.positionsStars=false;outbrain_template_manager.isAdMarking=true;this.adFieldsetId="outbrain_dual_ad_fs";this.adFieldsetClass="outbrain_dual_ad_class";
this.adUlElementId="outbrain_dual_ad_ul";this.adUlClassDual="outbrain_dual_ad_ul_class";this.regUlClassDual="outbrain_dual_reg_ul_class";this.adWhatsThisId="outbrain_dual_ad_whats";this.dividerId="outbrain_dual_divider";this.adWhatsThisClass="outbrain_dual_ad_whats_class";this.adWhatsThisHrfClass="outbrain_dual_ad_whats_A_class";this.buildDomDivider=function(){var a=[];a.push('<p id="'+this.dividerId+'_$INDEX_$TEMPLATE_NAME" style="height:5px;margin:0px;padding:0px;display:none"></p>');return a.join("")};
this.buildDomAdRecommendation=function(){var a=outbrain_browsers.ie&&(outbrain_browsers.ie8Doc8||outbrain_browsers.ie9Doc8Plus)?" outbrain_dual_ad_ul_ie8_class":"",b=[];b.push('<fieldset style="display:none;$FIELDSET_STYLE" id="'+this.adFieldsetId+'_$INDEX_$TEMPLATE_NAME" class="$FIELDSET_CLASS '+this.adFieldsetClass+'" >');b.push('    <legend class="$RECOMMENDATIONS_LEGEND_CLASS"></legend>');b.push('  \t<ul id="'+this.adUlElementId+'_$INDEX_$TEMPLATE_NAME" class="'+this.adUlClassDual+' $RECOMMENDATIONS_UL_CLASS" '+
a+">");b.push("  \t</ul>");b.push('    <div style="clear:both;" id="'+this.adWhatsThisId+'_$INDEX_$TEMPLATE_NAME" class="'+this.adWhatsThisClass+' " ></div>');b.push("</fieldset>");return b.join("")};this.buildDomRecommendations=function(a){var b=outbrain_settings.get(a,"adMarkingOnTop",true),c=[];if(b==true){c.push(this.buildDomAdRecommendation(a,"outbrain_dual_ul_ad_top"));c.push(this.buildDomDivider(a))}c.push('<fieldset style="display:none;$FIELDSET_STYLE" id="$FIELDSET_ID_$INDEX_$TEMPLATE_NAME" class="$FIELDSET_CLASS" >');
c.push('      <div id="$RECOMMENDATIONS_WAIT_ID_outer_$INDEX" class="$RECOMMENDATIONS_WAIT_CLASS_outer" style="display:none;"><div class="$RECOMMENDATIONS_WAIT_CLASS_inner">');c.push('               <p><img style="border:0px !important"/></p>');c.push("       </div></div>");c.push('       <legend class="$RECOMMENDATIONS_LEGEND_CLASS"></legend>');c.push('  \t<ul id="$RECOMMENDATIONS_UL_ID_$INDEX_$TEMPLATE_NAME" class="'+this.regUlClassDual+' $RECOMMENDATIONS_UL_CLASS" style="display:block">');c.push("  \t</ul>");
c.push("</fieldset>");c.push('<table id="$RECOMMENDATIONS_STATUS_ID_$INDEX_$TEMPLATE_NAME" class="$RECOMMENDATIONS_STATUS_TABLE_CLASS" style="display:none;"><tr><td>');c.push('\t<div id="$RECOMMENDATIONS_PC_LEGEND_$INDEX_$TEMPLATE_NAME" class="$RECOMMENDATIONS_PC_LEGENED_CLS" style="display:none;"></div>');c.push("</td><td>");c.push('\t<div id="$RECOMMENDATIONS_MORE_DIV_ID_$INDEX_$TEMPLATE_NAME" class="$RECOMMENDATIONS_MORE_LINK_DIV_CLASS" style="display:none;"></div>');c.push("</td></tr></table>");
if(b!=true){c.push(this.buildDomDivider(a));c.push(this.buildDomAdRecommendation(a,"outbrain_dual_ul_ad_bottom"))}return c.join("")};this.showRecommendations=function(a,b){var c=b.recTitle,g=b.jsonObj;c=this.changeStarsTextToImage(a,c,b.rankInfo.vote,true);if(!this.positionRec)return false;if(this.recommendationsShowBefore(a))this.recommendationsLegendUpdate(a,c);else{var e=this.getElementWithFullName(this.constants.recommendationsUlId,a);b=this.getElementWithFullName(this.adUlElementId,a);this.recommendationsLegendUpdate(a,
c);var f=outbrain_template_manager.getRecommendationsPerDoc(outbrain_template_manager.DATA_REC_REGULAR_ONLY,g.response.documents.doc,null,null);c=outbrain_template_manager.getRecommendationsPerDoc(outbrain_template_manager.DATA_REC_AD_ONLY,g.response.documents.doc,null,null);var d=outbrain_settings.get(a,"filterRegRecs",false),i=outbrain_template_manager.isAllSameSource(g.response.documents);d=typeof d=="boolean"&&d==true?0:f.length;var j=outbrain_settings.getNum(a,"defaultRecNumber"),l=j<=d?j:d;
j=d-l;var m=c.length;if(d>0)OB_widgetObjArray[a].SecLineOn=false;var n=e&&typeof e.opened=="boolean"&&e.opened==true;if(typeof OB_user_mode=="number"&&OB_user_mode==1){if(n)l=d;this.clearRecommendations(a,j)}for(var h=0;h<d;h++)this.renderOneRecommendation(a,e,f[h],h,i,h<l?true:false);for(e=0;e<m;e++){f=this.getCampType(a,g.response.documents);this.renderTitleAdRecommendation(a,b,e,g,f);this.renderOneRecommendation(a,b,c[e],h+e,i,true)}this.showHideElementByIdName(this.constants.fieldsetId,a,d>0);
this.showHideElementByIdName(this.dividerId,a,m>0&&d>0);this.setAdBoxPlace(a,m);this.checkIfMoreRecs(a,j,n);this.showHideRecsElements(a,g);this.enableBlogExternalElements(a);this.checkBottomTableWrapper(a)}};this.setAdBoxPlace=function(a,b){var c=this.getElementWithFullName(this.adFieldsetId,a);if(c&&c.style.display=="none"){c=outbrain_settings.get(a,"hookId",null);typeof c=="string"&&c.length>0&&b>0?this.hookAdsBox(c,a):this.showHideElementByIdName(this.adFieldsetId,a,b>0)}};this.recommendationsShowBefore=
function(a){var b=false;b=this.getElementWithFullName(this.constants.fieldsetId,a);var c=this.getElementWithFullName(this.adFieldsetId,a);b=b?b.style.display!="none"||c.style.display!="none":false;if(b==true&&typeof OB_user_mode=="number"&&OB_user_mode==1){this.removeWaitClock(a);b=false}return b};this.showHideRecsElements=function(a,b){this.setAdLegend(a,b);if(b=this.getElementWithFullName(this.constants.rateStatusInfoTableId,a))b.style.display="none";if(b=this.getElementWithFullName(this.constants.rateStatusInfoTdId,
a))b.style.display="none";if(b=this.getElementWithFullName(this.constants.fieldsetId,a))OB_widgetObjArray[a].hasRecommendations=true};this.renderTitleAdRecommendation=function(a,b,c,g,e){b=this.getpcName(a,g.response.documents);c="";c=e!=null&&e==2&&typeof outbrain_language_manager.getPiLegendText=="function"?outbrain_language_manager.getPiLegendText(a,b)+":":outbrain_language_manager.getPcLegendText(a,b)+":";this.adsLegendUpdate(a,c);this.adsWhatsThisUpdate(a)};this.adsWhatsThisUpdate=function(a){var b=
outbrain_language_manager.whatsThis(a),c='<a class="'+this.adWhatsThisHrfClass+'" href="javascript:void(0)" onClick="javascript:'+this.callForToolTip(a,"this",false)+'" >[$AD_TEXT]</a>';c=c.replace(/\$AD_TEXT/g,b);(a=this.getElementWithFullName(this.adWhatsThisId,a))&&k.dom.setInnerHTML(a,c)};this.showHideElementByIdName=function(a,b,c){if(a=this.getElementWithFullName(a,b))a.style.display=c?"block":"none"};this.adsLegendUpdate=function(a,b){if(a=this.getElementWithFullName(this.adFieldsetId,a))if((a=
a.getElementsByTagName("legend")[0])&&a.innerHTML!=b){a.className=this.constants.recommendationsLegendClass;k.dom.setInnerHTML(a,b)}};this.createLinkOfPC=function(){return""};this.isSonOf=function(a,b){if(a&&a.childNodes.length>0&&b){a=a.childNodes;for(var c=0;c<a.length;c++)if(a[c].id==b.id)return b}return null};this.hookAdsBox=function(a,b){var c=this.adFieldsetId+"_"+b+"_"+this.templateName,g=this.getElementWithFullName(this.constants.voterDivName,b);try{new outbrain_timeout(function(){if(document.getElementById(a+
"_"+b))return true;return false},function(){var f=document.getElementById(a+"_"+b);if(f){var d=document.getElementById(c);if(d){d.className+=outbrain_language_manager.isRtl(b)==true?" div-wrapper-right":" div-wrapper";k.cleanHookContainer(f,d);var i=d.cloneNode(true);f.appendChild(i);i.style.display="block";f.style.display="block";g.removeChild(d)}}},null,function(){var f=document.getElementById(c);if(f)f.style.display="block"},1E3,15,true)}catch(e){}};this.cleanHookContainer=function(a,b){try{if(this.isSonOf(a,
b)!==null)a.innerHTML=""}catch(c){}};this.resetTemplate=function(a){if(typeof OB_user_mode=="number"&&OB_user_mode==1){var b=this.getElementWithFullName(this.adFieldsetId,a);if(b)b.style.display="none";if(b=this.getElementWithFullName(this.constants.fieldsetId,a))b.style.display="none";if(b=this.getElementWithFullName(this.constants.recommendationsPcLegendId,a))b.style.display="none"}};this.clearRecommendations=function(a,b){var c=this.getElementWithFullName(this.adUlElementId,a);if(c!=null)c.innerHTML=
"";c=this.getElementWithFullName(this.constants.recommendationsUlId,a);if(c!=null)c.innerHTML="";a=this.getElementWithFullName(this.constants.recommendationsMoreDivId,a);if(a!=null&&b<1)a.innerHTML=""};this.showBalloon=false};outbrain_dual_template_object.prototype=outbrain_template_object;outbrain_dual_template_object.prototype.constructor=outbrain_dual_template_object;outbrain_dual_template_object.baseConstructor=outbrain_template_object;outbrain_template_manager.addTemplate({dual:outbrain_dual_template_object});
